### LIST

#GET
GET http://localhost:3020/usuario/4

### CREATE
POST http://localhost:3020/usuario/
Content-Type: application/json

{
    "email": "gabriel",
    "password": "1020302014",
    "logado": "1" 
}

### UPDATE
PATCH http://localhost:3000/unidades

### DELETE
DELETE http://localhost:3020/usuario/1
